# Generated by Django 4.0.1 on 2022-01-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='macAddress',
            new_name='macaddress',
        ),
    ]
