# Generated by Django 4.0.1 on 2022-01-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_rename_macaddress_sensors_macaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='controller_id',
            new_name='controller',
        ),
    ]
