# Generated by Django 4.0.4 on 2022-04-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('temp', models.FloatField(blank=True, default=0, null=True)),
                ('hum', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
